<h2>FAQ / Hilfe</h2>

<ul>
	<li><a href="#a_lieferung">Art und Dauer der Lieferung?</a></li>
	<li><a href="#a_versand">Wo wird geliefert und was kostet der Versand?</a></li>
	<li><a href="#a_info">Zusätzliche Informationen zum Versand</a></li>
	<li><a href="#a_zahlung">Welche Zahlungsmöglichkeiten werden mir angeboten?</a></li>
	<li><a href="#a_bankinfo">Bankverbindung</a></li>
	<li><a href="#a_contactus">Kontakt</a></li>
</ul>

<div>
	<h3 id="a_lieferung">Art und Dauer der Lieferung?</h3>
	<p>
		<img src="https://bienenkorb-shop.de/pub/media/wysiwyg/dhl-gogreen.jpg" alt="dhl_logo">
		<p><strong>Grundsätzlich versenden wir unsere Waren auschließlich mit DHL.</strong></p>
		
		<p>Zwischen Bestellannahme und Verpacken von sofort lieferbaren Artikeln liegen ca. 24 bis 48 Stunden. Hinzu kommt die Lieferzeit der DHL sowie mögliche Zeitverzögerungen durch Wochenende und Feiertage. Somit ergeben sich folgende Lieferzeiten bei sofort lieferbaren Artikeln:</p>
		
		<p><strong>Lieferung innerhalb Deutschlands:</strong> 1-2 Werktage </p>
		<p><strong>Lieferung ins Ausland:</strong> 4-10 Werktage </p>
		
		<p>Falls ein Produkt längere Lieferzeiten hat, wird dies auf der Detailseite des Produktes angezeigt.</p>
	</p>
</div>
<div>
	<h3 id="a_versand">Wo wird geliefert und was kostet der Versand?</h3>

	<p>	
	
		<table>
			<tr>
				<th>Zone</th>
				<th>Versandkosten</th>
				<th>kostenfreier Versand ab … Bestellwert</th>
			</tr>
			<tr>
				<td><strong>Deutschland</strong></td>
				<td>3,50 €</td>
				<td>ab 25,00 € frei</td>
			</tr>
			<tr>
				<td><strong>Österreich</strong></td>
				<td>5,90 €</td>
				<td>ab 100,00 € frei</td>
			</tr>
			<tr>
				<td><strong>Europa</strong></td>
				<td>9,90 €</td>
				<td>ab 150,00 € frei</td>
			</tr>
			<tr>
				<td><strong>Schweiz, Liechtenstein, Norwegen, Island</strong></td>
				<td>14,90 €</td>
				<td>ab 150,00 € frei</td>
			</tr>
		</table>
		
		<h4>Der Versand erfolgt ausschließlich in die obenstehenden Länder.</h4>

		<p>Jede Sendung ist versichert und kann meistens via Tracking Nummer (Sendungsverfolgung) in Echtzeit verfolgt werden.</p>

		<p>Bitte beachten Sie, dass bei Lieferungen in das Nicht-EU Ausland zusätzliche Zölle, Steuern und Gebühren anfallen. Weitere Informationen zu Zöllen finden Sie beispielsweise unter <a href="http://ec.europa.eu">http://ec.europa.eu</a> und zur Einfuhrumsatzsteuer unter <a href="http://auskunft.eztonline.de">http://auskunft.eztonline.de</a> sowie speziell für die Schweiz unter <a href="http://xtares.admin.ch">http://xtares.admin.ch</a>.</p>

		<p>Um zusätzliche Versandkosten zu minimieren, achten wir generell darauf, dass eine Bestellung mit unterschiedlichen Artikeln in einem Paket versendet wird. Sollten diese Artikel unterschiedliche Lieferzeiten haben, wird Ihr Paket versendet, sobald alle bestellten Artikel verfügbar sind. Bei längeren Lieferzeiten einzelner Artikel erfüllen wir auch gerne den Wunsch auf Teillieferung, wobei für diese Lieferungen zusätzliche Versandkosten berechnet werden. Bei fehlenden Angaben zur Lieferzeit vor Bestellung sowie bei unvorhersehbaren Lieferverzögerungen wird der Artikel nach Wareneingang versandkostenfrei an Sie versendet.</p>
	</p>
</div>
<div>
	<h3 id="a_info">Zusätzliche Informationen zum Versand</h3>
	<p>
		<h4>Packstationen</h4>

		<p>Eine Zustellung ist an Ihre DHL-Packstation möglich. Bitte geben Sie dafür während des Bestellvorganges die Daten Ihrer Packstation an.</p>

		<h4>Teillieferungen</h4>

		<p>Wenn wir Ihre Bestellung aus technischen Gründen in mehreren Teilen ausliefern, berechnen wir den Versandkostenanteil selbstverständlich nur einmal.</p>

		<p>DHL Go Green   Das GoGreen-Programm von DHL
		GoGreen leistet einen aktiven Beitrag zum Umweltschutz. Es werden alternative Fahrzeuge und Kraftstoffe eingesetzt. DHL GoGreen errechnet die CO2-Emissionen, die beim Transport unserer Sendungen enstehen, auf Basis der Richtlinien des Koyoto Protokolls. Diese Emissionen werden neutralisiert durch Investitionen in Umweltprojekte wie z.B. die Aufforstung des Regenwaldes. So konnten wir im Jahr 2009 17,27 Tonnen und im Jahr 2010 63,5 Tonnen CO2 kompensieren.</p>
	</p>
</div>
<div>
	<h3 id="a_zahlung">Welche Zahlungsmöglichkeiten werden mir angeboten?</h3>
	<p>
		<p>4.1. Für Lieferungen innerhalb Deutschlands bieten wir folgende Zahlungsmöglichkeiten an, sofern in der jeweiligen Produktdarstellung im Angebot nichts anderes bestimmt ist:</p>
		<ul>
			<li>Zahlung per Vorkasse ( -4% Skonto)</li>
			<li>Pay-Pal / Pay-Pal Express</li>
			<li>Lastschrift durch Pay-Pal-Service für das Sie kein Pay-Pal-Konto benötigen</li>
			<li>Kreditkarte durch Pay-Pal-Service für das Sie kein Pay-Pal-Konto benötigen (Visa, Mastercard, American Express)</li>
			<li>Kauf auf Rechnung durch Pay-Pal-Service für das Sie kein Pay-Pal-Konto benötigen</li>
			<li>Amazon-Payments</li>
			<li>Barzahlung oder per EC-Karte bei Abholung in unserem Ladenlokal*</li>
		</ul>
		
		<p>4.2. Für Lieferungen ins Ausland bieten wir folgende Zahlungsmöglichkeiten an, sofern in der jeweiligen Produktdarstellung im Angebot nichts anderes bestimmt ist:</p>
		<ul>
			<li>Zahlung per Vorkasse ( -4% Skonto)</li>
			<li>Pay-Pal / Pay-Pal Express</li>
			<li>Lastschrift durch Pay-Pal-Service für das Sie kein Pay-Pal-Konto benötigen</li>
			<li>Kreditkarte durch Pay-Pal-Service für das Sie kein Pay-Pal-Konto benötigen (Visa, Mastercard, American Express)</li>
			<li>Kauf auf Rechnung durch Pay-Pal-Service für das Sie kein Pay-Pal-Konto benötigen</li>
			<li>Amazon-Payments</li>
		</ul>
	</p>
</div>
<div>
	<h3 id="a_bankinfo">Bankverbindung</h3>

	<p>
		<strong>
			AUGSBURGER AKTIENBANK<br>
			Inhaber: BIENENKORB24 - Henk Schneider<br>
			IBAN: DE67 2009 0500 0002 0617 32<br>
			BIC: AUGBDE71NET
		</strong>		
	</p>

	<p>Bitte geben Sie bei Vorkasse-Überweisungen Ihre Bestellnummer als Verwendungszweck an.</p>
</div>
<div>
	<h3 id="a_contactus">Kontakt</h3>
	<p>
		<p> <strong>Zu Bestellungen deutschlandweit?</strong></p>

		<p>Tel: (+49) (0)271 - 23 18 900<br>
		<a href="kontakt@bienenkorb-shop.de">kontakt@bienenkorb-shop.de</a></p>

		<p> <strong>Zu Auslandsbestellungen?</strong></p>

		<p>Tel: (+49) (0)271 - 23 18 900<br>
		<a href="kontakt@bienenkorb-shop.de">kontakt@bienenkorb-shop.de</a></p>
	</p>
</div>