<h2>Impressum</h2>
<p>BIENENKORB24 e.K.</p>
<p>Inhaber: Henk Schneider</p>
<p>Sandstr. 31<br />57072 Siegen<br />Deutschland</p>
<p>Telefon: +49 (0271) 2318900</p>
<p>Fax: +49 (0271) 2318601</p>
<p>E-Mail: <a href="mailto:kontakt@bienenkorb-shop.de">kontakt@bienenkorb-shop.de</a></p>
<p>Handelsregister: Amtsgericht Siegen, HRA 8929</p>
<p>Umsatzsteuer-Identifikationsnummer: DE 815450379</p>
<p>Die Europ&auml;ische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit, die Sie hier finden <a href="https://ec.europa.eu/consumers/odr/">https://ec.europa.eu/consumers/odr/</a>.&nbsp;<br />Wir sind bereit, an einem au&szlig;ergerichtlichen Schlichtungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.<br />Zust&auml;ndig ist die Allgemeine Verbraucherschlichtungsstelle (ab dem 01.01.2020: die Universalschlichtungsstelle) des Zentrums f&uuml;r Schlichtung e.V., Stra&szlig;burger Stra&szlig;e 8, 77694 Kehl am Rhein, <a href="http://www.verbraucher-schlichter.de">www.verbraucher-schlichter.de</a>.</p>