<h2>Zahlungs- und Versandinformationen, Zahlarten und Versandkosten</h2>

<h3>1. Zahlungsm&ouml;glichkeiten</h3>
<p>1.1. F&uuml;r Lieferungen innerhalb Deutschlands bieten wir folgende Zahlungsm&ouml;glichkeiten an, sofern in der jeweiligen Produktdarstellung im Angebot nichts anderes bestimmt ist:</p>
<p>- Zahlung per Vorkasse ( -4% Skonto)<br />- Paypal / Paypal Express<br />- Kreditkarte (Visa, Mastercard, American Express)<br />- Kauf auf Rechnung (PayPal)<br />- Amazon-Payments<br />- Barzahlung oder per EC-Karte bei Abholung in unserem Ladenlokal*</p>
<p>1.2. F&uuml;r Lieferungen ins Ausland bieten wir folgende Zahlungsm&ouml;glichkeiten an, sofern in der jeweiligen Produktdarstellung im Angebot nichts anderes bestimmt ist:</p>
<p>- Zahlung per Vorkasse ( -4% Skonto)<br />- Paypal / Paypal Express<br />- Kreditkarte (Visa, Mastercard, American Express)<br />- Kauf auf Rechnung (PayPal)<br />- Amazon-Payments</p>

<h3>2. Lieferung</h3>
<p>2.1. Der Versand Ihrer Bestellung erfolgt per DHL<br />2.2. Wir versenden in folgende L&auml;nder: Deutschland, Deutschland, Island, Liechtenstein, Norwegen, &Ouml;sterreich, Schweiz, Europ&auml;ische Union Die jeweils anfallenden Versandkosten finden Sie unter dem Punkt 3.1 und 3.2</p>

<h3>3. Versandkosten</h3>
<p>3.1. Die Versandkosten innerhalb Deutschlands bemessen sich nach dem Gesamtpreis.<br />Bestellungen im Wert von 0 bis 24,99 &euro; Euro = 3,00 Euro<br />Bestellungen im Wert ab 25,00 Euro = versandkostenfrei</p>
<p>3.2. Bei Selbstabholung informiert der Verk&auml;ufer den K&auml;ufer zun&auml;chst per Email dar&uuml;ber, dass die von ihm bestellte Ware zur Abholung bereit steht. Nach Erhalt dieser Email kann der K&auml;ufer die Ware nach Absprache mit dem Verk&auml;ufer abholen. In diesem Fall werden keine Versandkosten berechnet.</p>
<p>3.3. Bei Zahlung per Vorauskasse (Vorab&uuml;berweisung) gew&auml;hrt der Verk&auml;ufer 4,00 % Skonto auf den Bruttowarenwert der jeweiligen Bestellung. Ab einem Bruttobestellwert von 25 EUR versenden wir frachtfrei.</p>
<p>3.5. Bitte beachten Sie, dass bei grenz&uuml;berschreitenden Lieferungen weitere Steuern (etwa im Fall eines innergemeinschaftlichen Erwerbs) und/oder Abgaben, etwa in Form von Z&ouml;llen anfallen k&ouml;nnen, die von Ihnen zu tragen sind.</p>
<table>
<tbody>
	<tr>
		<th>Zone</th>
		<th>Versandkosten</th>
		<th>kostenfreier Versand ab &hellip; Bestellwert</th>
	</tr>
	<tr>
		<td><strong>Deutschland</strong></td>
		<td>3,50 &euro;</td>
		<td>ab 25,00 &euro; frei</td>
	</tr>
	<tr>
		<td><strong>&Ouml;sterreich</strong></td>
		<td>5,90 &euro;</td>
		<td>ab 100,00 &euro; frei</td>
	</tr>
	<tr>
		<td><strong>Europa</strong></td>
		<td>9,90 &euro;</td>
		<td>ab 150,00 &euro; frei</td>
	</tr>
	<tr>
		<td><strong>Schweiz, Liechtenstein, Norwegen, Island</strong></td>
		<td>14,90 &euro;</td>
		<td>ab 150,00 &euro; frei</td>
	</tr>
</tbody>
</table>