<div style="background-color: white">
    <table id="footer-table">
        <tr>
            <th class="centered_text"><h5>service & kontakt</h5></th>
            <th class="centered_text"><h5>informationen</h5></th>
            <th class="centered_text"><h5>bienenkorb 24</h5></th>
        </tr>
        <tr>
            <td class="bk-footer-data">servicehotline</td>
            <td class="bk-footer-data"><a href="<?php echo $block->getUrl('versand', ['_secure' => true]);?>">versandinformation</a></td>
            <td class="bk-footer-data">über uns</td>
        </tr>
        <tr>
            <td class="bk-footer-data"><b>0271 - 23 18 900</b></td>
            <td class="bk-footer-data">zahlungsinformation</td>
            <td class="bk-footer-data">Anmeldung newsletter</td>
        </tr>
        <tr>
            <td class="bk-footer-data"><a href="<?php echo $block->getUrl('feedback', ['_secure' => true]);?>">feedback-formular</a></td>
            <td class="bk-footer-data"><a href="<?php echo $block->getUrl('widerruf', ['_secure' => true]);?>">widerrufbelehrung</a></td>
            <td class="bk-footer-data"><a href="<?php echo $block->getUrl('datenschutz', ['_secure' => true]);?>">datenschutz + cookies</a></td>
        </tr>
        <tr>
            <td class="bk-footer-data"><a href="<?php echo $block->getUrl('faq', ['_secure' => true]);?>">häufige fragen (FAQ)</a></td>
            <td class="bk-footer-data"><a href="<?php echo $block->getUrl('agb', ['_secure' => true]);?>">AGB</a></td>
            <td class="bk-footer-data"><a href="<?php echo $block->getUrl('impressum', ['_secure' => true]);?>">impressum</a></td>
        </tr>
        <tr><td></td></tr>
    </table>
</div>