<div class="bk-footer">
    <div>
    <table style="text-align: center;">
        <!-- <tbody style="align: right;"> -->
        <tr>
            <th class="bk_footer_header">service & kontakt</th>
            <th class="bk_footer_header">informationen</th>
            <th class="bk_footer_header">bienenkorb 24</th>
        </tr>
        <tr>
            <td>
                TD1
            </td>
            <td>
            TD2
            </td>
            <td>
            TD3
            </td>
        </tr>
        <!-- </tbody> -->
        </table>
    </div>
</div>