<div style="background-color: white">
    <table id="footer-table">
        <tr>
            <th class="centered_text"><h5>service & kontakt</h5></th>
            <th class="centered_text"><h5>informationen</h5></th>
            <th class="centered_text"><h5>bienenkorb 24</h5></th>
        </tr>
        <tr>
            <td class="bk-footer-data">servicehotline</td>
            <td class="bk-footer-data">versandinformation</td>
            <td class="bk-footer-data">über uns</td>
        </tr>
        <tr>
            <td class="bk-footer-data"><b>0271 - 23 18 900</b></td>
            <td class="bk-footer-data">zahlungsinformation</td>
            <td class="bk-footer-data">Anmeldung newsletter</td>
        </tr>
        <tr>
            <td class="bk-footer-data">feedback-formular</td>
            <td class="bk-footer-data">wiederrufbelehrung</td>
            <td class="bk-footer-data">datenschutz + cookies</td>
        </tr>
        <tr>
            <td class="bk-footer-data"><a href="<?php echo $block->getUrl('faq', ['_secure' => true]);?>">häufige fragen (FAQ)</a></td>
            <td class="bk-footer-data">AGB</td>
            <td class="bk-footer-data">impressum</td>
        </tr>
        <tr><td></td></tr>
    </table>
</div>