<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
<div class="additional-attributes-wrapper table-wrapper">
    <table class="data table additional-attributes" id="product-attribute-specs-table">
        <caption class="table-caption"><?= $block->escapeHtml(__('More Information')) ?></caption>
        <tbody>
            <?php foreach ($_additional as $_data) :?>
            <tr>
                <th class="col label" scope="row"><?= $block->escapeHtml($_data['label']) ?></th>
                <td class="col data" data-th="<?= $block->escapeHtmlAttr($_data['label']) ?>">
                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif;?>
<?php
        $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
            ->init($block->getProduct(), 'product_page_image_large')
            ->setImageFile($block->getImageFile())
            ->getUrl();
    ?>
<meta itemprop="image" content="<?php /* @escapeNotVerified */ echo $imageUrl; ?>">
<div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
    <meta itemprop="price" content="<?php echo $_product->getFinalPrice(); ?>" />
    <meta itemprop="priceCurrency" content="<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
  echo $currency = $currencysymbol->getStore()->getCurrentCurrencyCode(); ?>" />
    <meta itemprop="priceCurrency" content="<?php echo $_product->getCurrencyCode() ?>" />
    <meta itemprop="url" content="<?php echo $_product->getProductUrl(); ?>">
    <meta itemprop="itemCondition" content="https://schema.org/NewCondition" />

    <?php if ($_product->isAvailable()): ?>
    <link itemprop="availability" href="http://schema.org/InStock">
    <?php else: ?>
    <link itemprop="availability" href="http://schema.org/OutOfStock">
    <?php endif; ?>
</div>